http:
  routers:
    vesla-api:
      rule: "Host(`api.vesla-app.site`)"
      entryPoints:
        - websecure
      service: vesla-api-service
      tls:
        certResolver: digitalocean

  services:
    vesla-api-service:
      loadBalancer:
        servers:
          - url: "http://vesla-api:5001"
